# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chronoqueue.api.queueservice.v1 import (
    request_response_pb2 as proto_dot_queueservice_dot_v1_dot_request__response__pb2,
)


class QueueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateQueue = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/CreateQueue",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateQueueRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateQueueResponse.FromString,
        )
        self.DeleteQueue = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteQueue",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteQueueRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteQueueResponse.FromString,
        )
        self.ListQueues = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/ListQueues",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListQueuesRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListQueuesResponse.FromString,
        )
        self.GetQueueState = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetQueueState",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetQueueStateRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetQueueStateResponse.FromString,
        )
        self.PostMessage = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/PostMessage",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessageRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessageResponse.FromString,
        )
        self.GetNextMessage = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetNextMessage",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetNextMessageRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetNextMessageResponse.FromString,
        )
        self.AcknowledgeMessage = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/AcknowledgeMessage",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.AcknowledgeMessageRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.AcknowledgeMessageResponse.FromString,
        )
        self.RenewMessageLease = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/RenewMessageLease",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RenewMessageLeaseRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RenewMessageLeaseResponse.FromString,
        )
        self.PeekQueueMessages = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/PeekQueueMessages",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PeekQueueMessagesRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PeekQueueMessagesResponse.FromString,
        )
        self.SendMessageHeartBeat = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/SendMessageHeartBeat",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.SendMessageHeartBeatRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.SendMessageHeartBeatResponse.FromString,
        )
        self.CreateSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/CreateSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateScheduleResponse.FromString,
        )
        self.DeleteSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteScheduleResponse.FromString,
        )
        self.GetSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleResponse.FromString,
        )
        self.ListSchedules = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/ListSchedules",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchedulesRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchedulesResponse.FromString,
        )
        self.GetScheduleHistory = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetScheduleHistory",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleHistoryRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleHistoryResponse.FromString,
        )
        self.PauseSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/PauseSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PauseScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PauseScheduleResponse.FromString,
        )
        self.ResumeSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/ResumeSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ResumeScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ResumeScheduleResponse.FromString,
        )
        self.GetDLQMessages = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetDLQMessages",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQMessagesRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQMessagesResponse.FromString,
        )
        self.RequeueFromDLQ = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/RequeueFromDLQ",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RequeueFromDLQRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RequeueFromDLQResponse.FromString,
        )
        self.DeleteFromDLQ = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteFromDLQ",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteFromDLQRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteFromDLQResponse.FromString,
        )
        self.PurgeDLQ = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/PurgeDLQ",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PurgeDLQRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PurgeDLQResponse.FromString,
        )
        self.GetDLQStats = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetDLQStats",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQStatsRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQStatsResponse.FromString,
        )
        self.ValidateCalendarSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/ValidateCalendarSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidateCalendarScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidateCalendarScheduleResponse.FromString,
        )
        self.PreviewCalendarSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/PreviewCalendarSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PreviewCalendarScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PreviewCalendarScheduleResponse.FromString,
        )
        self.RegisterSchema = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/RegisterSchema",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RegisterSchemaRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RegisterSchemaResponse.FromString,
        )
        self.GetSchema = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetSchema",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetSchemaRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetSchemaResponse.FromString,
        )
        self.ListSchemas = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/ListSchemas",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchemasRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchemasResponse.FromString,
        )
        self.DeleteSchema = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteSchema",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteSchemaRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteSchemaResponse.FromString,
        )
        self.ValidatePayload = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/ValidatePayload",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidatePayloadRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidatePayloadResponse.FromString,
        )


class QueueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateQueue(self, request, context):
        """Queue Management Operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListQueues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetQueueState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PostMessage(self, request, context):
        """Message Operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetNextMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AcknowledgeMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RenewMessageLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PeekQueueMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendMessageHeartBeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateSchedule(self, request, context):
        """Schedule Management Operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetScheduleHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PauseSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResumeSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDLQMessages(self, request, context):
        """Dead Letter Queue Management Operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RequeueFromDLQ(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteFromDLQ(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PurgeDLQ(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDLQStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateCalendarSchedule(self, request, context):
        """Calendar Schedule Operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PreviewCalendarSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RegisterSchema(self, request, context):
        """Schema Management Operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListSchemas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidatePayload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateQueue": grpc.unary_unary_rpc_method_handler(
            servicer.CreateQueue,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateQueueRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateQueueResponse.SerializeToString,
        ),
        "DeleteQueue": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteQueue,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteQueueRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteQueueResponse.SerializeToString,
        ),
        "ListQueues": grpc.unary_unary_rpc_method_handler(
            servicer.ListQueues,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListQueuesRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListQueuesResponse.SerializeToString,
        ),
        "GetQueueState": grpc.unary_unary_rpc_method_handler(
            servicer.GetQueueState,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetQueueStateRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetQueueStateResponse.SerializeToString,
        ),
        "PostMessage": grpc.unary_unary_rpc_method_handler(
            servicer.PostMessage,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessageRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessageResponse.SerializeToString,
        ),
        "GetNextMessage": grpc.unary_unary_rpc_method_handler(
            servicer.GetNextMessage,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetNextMessageRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetNextMessageResponse.SerializeToString,
        ),
        "AcknowledgeMessage": grpc.unary_unary_rpc_method_handler(
            servicer.AcknowledgeMessage,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.AcknowledgeMessageRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.AcknowledgeMessageResponse.SerializeToString,
        ),
        "RenewMessageLease": grpc.unary_unary_rpc_method_handler(
            servicer.RenewMessageLease,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RenewMessageLeaseRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RenewMessageLeaseResponse.SerializeToString,
        ),
        "PeekQueueMessages": grpc.unary_unary_rpc_method_handler(
            servicer.PeekQueueMessages,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PeekQueueMessagesRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PeekQueueMessagesResponse.SerializeToString,
        ),
        "SendMessageHeartBeat": grpc.unary_unary_rpc_method_handler(
            servicer.SendMessageHeartBeat,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.SendMessageHeartBeatRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.SendMessageHeartBeatResponse.SerializeToString,
        ),
        "CreateSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.CreateSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateScheduleResponse.SerializeToString,
        ),
        "DeleteSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteScheduleResponse.SerializeToString,
        ),
        "GetSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.GetSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleResponse.SerializeToString,
        ),
        "ListSchedules": grpc.unary_unary_rpc_method_handler(
            servicer.ListSchedules,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchedulesRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchedulesResponse.SerializeToString,
        ),
        "GetScheduleHistory": grpc.unary_unary_rpc_method_handler(
            servicer.GetScheduleHistory,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleHistoryRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleHistoryResponse.SerializeToString,
        ),
        "PauseSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.PauseSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PauseScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PauseScheduleResponse.SerializeToString,
        ),
        "ResumeSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.ResumeSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ResumeScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ResumeScheduleResponse.SerializeToString,
        ),
        "GetDLQMessages": grpc.unary_unary_rpc_method_handler(
            servicer.GetDLQMessages,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQMessagesRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQMessagesResponse.SerializeToString,
        ),
        "RequeueFromDLQ": grpc.unary_unary_rpc_method_handler(
            servicer.RequeueFromDLQ,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RequeueFromDLQRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RequeueFromDLQResponse.SerializeToString,
        ),
        "DeleteFromDLQ": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteFromDLQ,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteFromDLQRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteFromDLQResponse.SerializeToString,
        ),
        "PurgeDLQ": grpc.unary_unary_rpc_method_handler(
            servicer.PurgeDLQ,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PurgeDLQRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PurgeDLQResponse.SerializeToString,
        ),
        "GetDLQStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetDLQStats,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQStatsRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQStatsResponse.SerializeToString,
        ),
        "ValidateCalendarSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateCalendarSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidateCalendarScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidateCalendarScheduleResponse.SerializeToString,
        ),
        "PreviewCalendarSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.PreviewCalendarSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PreviewCalendarScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PreviewCalendarScheduleResponse.SerializeToString,
        ),
        "RegisterSchema": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterSchema,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RegisterSchemaRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RegisterSchemaResponse.SerializeToString,
        ),
        "GetSchema": grpc.unary_unary_rpc_method_handler(
            servicer.GetSchema,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetSchemaRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetSchemaResponse.SerializeToString,
        ),
        "ListSchemas": grpc.unary_unary_rpc_method_handler(
            servicer.ListSchemas,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchemasRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchemasResponse.SerializeToString,
        ),
        "DeleteSchema": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteSchema,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteSchemaRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteSchemaResponse.SerializeToString,
        ),
        "ValidatePayload": grpc.unary_unary_rpc_method_handler(
            servicer.ValidatePayload,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidatePayloadRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidatePayloadResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "chronoqueue.api.queueservice.v1.QueueService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateQueue(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/CreateQueue",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateQueueRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeleteQueue(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteQueue",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteQueueRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListQueues(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/ListQueues",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListQueuesRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListQueuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetQueueState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetQueueState",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetQueueStateRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetQueueStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PostMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/PostMessage",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessageRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetNextMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetNextMessage",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetNextMessageRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetNextMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AcknowledgeMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/AcknowledgeMessage",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.AcknowledgeMessageRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.AcknowledgeMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RenewMessageLease(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/RenewMessageLease",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.RenewMessageLeaseRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.RenewMessageLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PeekQueueMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/PeekQueueMessages",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PeekQueueMessagesRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PeekQueueMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SendMessageHeartBeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/SendMessageHeartBeat",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.SendMessageHeartBeatRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.SendMessageHeartBeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CreateSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/CreateSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeleteSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListSchedules(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/ListSchedules",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchedulesRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetScheduleHistory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetScheduleHistory",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleHistoryRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PauseSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/PauseSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PauseScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PauseScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ResumeSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/ResumeSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ResumeScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ResumeScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetDLQMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetDLQMessages",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQMessagesRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RequeueFromDLQ(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/RequeueFromDLQ",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.RequeueFromDLQRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.RequeueFromDLQResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeleteFromDLQ(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteFromDLQ",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteFromDLQRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteFromDLQResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PurgeDLQ(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/PurgeDLQ",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PurgeDLQRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PurgeDLQResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetDLQStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetDLQStats",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQStatsRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ValidateCalendarSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/ValidateCalendarSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidateCalendarScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidateCalendarScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PreviewCalendarSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/PreviewCalendarSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PreviewCalendarScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PreviewCalendarScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RegisterSchema(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/RegisterSchema",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.RegisterSchemaRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.RegisterSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetSchema(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetSchema",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetSchemaRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListSchemas(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/ListSchemas",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchemasRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchemasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeleteSchema(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteSchema",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteSchemaRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ValidatePayload(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/ValidatePayload",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidatePayloadRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidatePayloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
