# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common/v1/common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cproto/common/v1/common.proto\x12\x19\x63hronoqueue.api.common.v1\x1a\x1cgoogle/protobuf/struct.proto"\xfe\x01\n\x07Payload\x12\x42\n\x08metadata\x18\x01 \x03(\x0b\x32\x30.chronoqueue.api.common.v1.Payload.MetadataEntry\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12\x11\n\tschema_id\x18\x04 \x01(\t\x12\x16\n\x0eschema_version\x18\x05 \x01(\x05\x1aG\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\x42\x36Z4github.com/adrien19/chronoqueue/api/common/v1;commonb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.common.v1.common_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z4github.com/adrien19/chronoqueue/api/common/v1;common"
    _globals["_PAYLOAD_METADATAENTRY"]._options = None
    _globals["_PAYLOAD_METADATAENTRY"]._serialized_options = b"8\001"
    _globals["_PAYLOAD"]._serialized_start = 90
    _globals["_PAYLOAD"]._serialized_end = 344
    _globals["_PAYLOAD_METADATAENTRY"]._serialized_start = 273
    _globals["_PAYLOAD_METADATAENTRY"]._serialized_end = 344
# @@protoc_insertion_point(module_scope)
