"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class CreateQueueRequest(google.protobuf.message.Message):
    """Create queue"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_FIELD_NUMBER: builtins.int
    @property
    def queue(self) -> global___Queue: ...
    def __init__(
        self,
        *,
        queue: global___Queue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["queue", b"queue"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["queue", b"queue"]) -> None: ...

global___CreateQueueRequest = CreateQueueRequest

@typing_extensions.final
class CreateQueueResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CreateQueueResponse = CreateQueueResponse

@typing_extensions.final
class DeleteQueueRequest(google.protobuf.message.Message):
    """Delete queue by name"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___DeleteQueueRequest = DeleteQueueRequest

@typing_extensions.final
class DeleteQueueResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DeleteQueueResponse = DeleteQueueResponse

@typing_extensions.final
class PostMessageRequest(google.protobuf.message.Message):
    """Post a message to the queue"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_NAME_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    queue_name: builtins.str
    @property
    def message(self) -> global___Message: ...
    def __init__(
        self,
        *,
        queue_name: builtins.str = ...,
        message: global___Message | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "queue_name", b"queue_name"]) -> None: ...

global___PostMessageRequest = PostMessageRequest

@typing_extensions.final
class PostMessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PostMessageResponse = PostMessageResponse

@typing_extensions.final
class Payload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.bytes
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    METADATA_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.bytes]: ...
    data: builtins.bytes
    def __init__(
        self,
        *,
        metadata: collections.abc.Mapping[builtins.str, builtins.bytes] | None = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "metadata", b"metadata"]) -> None: ...

global___Payload = Payload

@typing_extensions.final
class Message(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Metadata(google.protobuf.message.Message):
        """payload should be a json or any"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _State:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Message.Metadata._State.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            UNDEFINED: Message.Metadata._State.ValueType  # 0
            INVISIBLE: Message.Metadata._State.ValueType  # 1
            PENDING: Message.Metadata._State.ValueType  # 2
            RUNNING: Message.Metadata._State.ValueType  # 3
            COMPLETED: Message.Metadata._State.ValueType  # 4
            CANCELED: Message.Metadata._State.ValueType  # 5
            ERRORED: Message.Metadata._State.ValueType  # 6

        class State(_State, metaclass=_StateEnumTypeWrapper): ...
        UNDEFINED: Message.Metadata.State.ValueType  # 0
        INVISIBLE: Message.Metadata.State.ValueType  # 1
        PENDING: Message.Metadata.State.ValueType  # 2
        RUNNING: Message.Metadata.State.ValueType  # 3
        COMPLETED: Message.Metadata.State.ValueType  # 4
        CANCELED: Message.Metadata.State.ValueType  # 5
        ERRORED: Message.Metadata.State.ValueType  # 6

        PAYLOAD_FIELD_NUMBER: builtins.int
        STATE_FIELD_NUMBER: builtins.int
        INVISIBILITY_DURATION_FIELD_NUMBER: builtins.int
        ATTEMPTS_LEFT_FIELD_NUMBER: builtins.int
        LEASE_DURATION_FIELD_NUMBER: builtins.int
        LEASE_EXPIRY_FIELD_NUMBER: builtins.int
        @property
        def payload(self) -> global___Payload:
            """google.protobuf.Struct payload = 1;"""
        state: global___Message.Metadata.State.ValueType
        invisibility_duration: builtins.int
        attempts_left: builtins.int
        lease_duration: builtins.int
        lease_expiry: builtins.int
        def __init__(
            self,
            *,
            payload: global___Payload | None = ...,
            state: global___Message.Metadata.State.ValueType = ...,
            invisibility_duration: builtins.int = ...,
            attempts_left: builtins.int = ...,
            lease_duration: builtins.int | None = ...,
            lease_expiry: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_lease_duration", b"_lease_duration", "_lease_expiry", b"_lease_expiry", "lease_duration", b"lease_duration", "lease_expiry", b"lease_expiry", "payload", b"payload"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_lease_duration", b"_lease_duration", "_lease_expiry", b"_lease_expiry", "attempts_left", b"attempts_left", "invisibility_duration", b"invisibility_duration", "lease_duration", b"lease_duration", "lease_expiry", b"lease_expiry", "payload", b"payload", "state", b"state"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_lease_duration", b"_lease_duration"]) -> typing_extensions.Literal["lease_duration"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_lease_expiry", b"_lease_expiry"]) -> typing_extensions.Literal["lease_expiry"] | None: ...

    MESSAGE_ID_FIELD_NUMBER: builtins.int
    PRIORITY_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    message_id: builtins.str
    priority: builtins.int
    @property
    def metadata(self) -> global___Message.Metadata: ...
    def __init__(
        self,
        *,
        message_id: builtins.str = ...,
        priority: builtins.int = ...,
        metadata: global___Message.Metadata | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["metadata", b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message_id", b"message_id", "metadata", b"metadata", "priority", b"priority"]) -> None: ...

global___Message = Message

@typing_extensions.final
class GetNextMessageRequest(google.protobuf.message.Message):
    """Get the next message on the queue"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_NAME_FIELD_NUMBER: builtins.int
    LEASE_DURATION_FIELD_NUMBER: builtins.int
    queue_name: builtins.str
    lease_duration: builtins.int
    def __init__(
        self,
        *,
        queue_name: builtins.str = ...,
        lease_duration: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["lease_duration", b"lease_duration", "queue_name", b"queue_name"]) -> None: ...

global___GetNextMessageRequest = GetNextMessageRequest

@typing_extensions.final
class GetNextMessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> global___Message: ...
    def __init__(
        self,
        *,
        message: global___Message | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message"]) -> None: ...

global___GetNextMessageResponse = GetNextMessageResponse

@typing_extensions.final
class AcknowledgeMessageRequest(google.protobuf.message.Message):
    """Acknowledge the message on the queue"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_NAME_FIELD_NUMBER: builtins.int
    MESSAGE_ID_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    queue_name: builtins.str
    message_id: builtins.str
    state: global___Message.Metadata.State.ValueType
    def __init__(
        self,
        *,
        queue_name: builtins.str = ...,
        message_id: builtins.str = ...,
        state: global___Message.Metadata.State.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message_id", b"message_id", "queue_name", b"queue_name", "state", b"state"]) -> None: ...

global___AcknowledgeMessageRequest = AcknowledgeMessageRequest

@typing_extensions.final
class AcknowledgeMessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AcknowledgeMessageResponse = AcknowledgeMessageResponse

@typing_extensions.final
class RenewMessageLeaseRequest(google.protobuf.message.Message):
    """Renew lease period of a message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_NAME_FIELD_NUMBER: builtins.int
    MESSAGE_ID_FIELD_NUMBER: builtins.int
    LEASE_DURATION_FIELD_NUMBER: builtins.int
    queue_name: builtins.str
    message_id: builtins.str
    lease_duration: builtins.int
    def __init__(
        self,
        *,
        queue_name: builtins.str = ...,
        message_id: builtins.str = ...,
        lease_duration: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["lease_duration", b"lease_duration", "message_id", b"message_id", "queue_name", b"queue_name"]) -> None: ...

global___RenewMessageLeaseRequest = RenewMessageLeaseRequest

@typing_extensions.final
class RenewMessageLeaseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RenewMessageLeaseResponse = RenewMessageLeaseResponse

@typing_extensions.final
class PeekQueueMessagesRequest(google.protobuf.message.Message):
    """View pending messages on a queueu"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class PriorityRange(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MIN_FIELD_NUMBER: builtins.int
        MAX_FIELD_NUMBER: builtins.int
        min: builtins.int
        max: builtins.int
        def __init__(
            self,
            *,
            min: builtins.int = ...,
            max: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["max", b"max", "min", b"min"]) -> None: ...

    QUEUE_NAME_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    PRIORITY_RANGE_FIELD_NUMBER: builtins.int
    queue_name: builtins.str
    limit: builtins.int
    @property
    def priority_range(self) -> global___PeekQueueMessagesRequest.PriorityRange: ...
    def __init__(
        self,
        *,
        queue_name: builtins.str = ...,
        limit: builtins.int = ...,
        priority_range: global___PeekQueueMessagesRequest.PriorityRange | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_priority_range", b"_priority_range", "priority_range", b"priority_range"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_priority_range", b"_priority_range", "limit", b"limit", "priority_range", b"priority_range", "queue_name", b"queue_name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_priority_range", b"_priority_range"]) -> typing_extensions.Literal["priority_range"] | None: ...

global___PeekQueueMessagesRequest = PeekQueueMessagesRequest

@typing_extensions.final
class PeekQueueMessagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGES_FIELD_NUMBER: builtins.int
    @property
    def messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Message]: ...
    def __init__(
        self,
        *,
        messages: collections.abc.Iterable[global___Message] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["messages", b"messages"]) -> None: ...

global___PeekQueueMessagesResponse = PeekQueueMessagesResponse

@typing_extensions.final
class GetQueueStateRequest(google.protobuf.message.Message):
    """vew the state of a given queue"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_NAME_FIELD_NUMBER: builtins.int
    queue_name: builtins.str
    def __init__(
        self,
        *,
        queue_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["queue_name", b"queue_name"]) -> None: ...

global___GetQueueStateRequest = GetQueueStateRequest

@typing_extensions.final
class GetQueueStateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INVISIBLE_MESSAGES_COUNT_FIELD_NUMBER: builtins.int
    PENDING_MESSAGES_COUNT_FIELD_NUMBER: builtins.int
    RUNNING_MESSAGES_COUNT_FIELD_NUMBER: builtins.int
    COMPLETED_MESSAGES_COUNT_FIELD_NUMBER: builtins.int
    CANCELED_MESSAGES_COUNT_FIELD_NUMBER: builtins.int
    ERRORED_MESSAGES_COUNT_FIELD_NUMBER: builtins.int
    EARLIEST_DEADLINE_FIELD_NUMBER: builtins.int
    invisible_messages_count: builtins.int
    pending_messages_count: builtins.int
    running_messages_count: builtins.int
    completed_messages_count: builtins.int
    canceled_messages_count: builtins.int
    errored_messages_count: builtins.int
    @property
    def earliest_deadline(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        invisible_messages_count: builtins.int = ...,
        pending_messages_count: builtins.int = ...,
        running_messages_count: builtins.int = ...,
        completed_messages_count: builtins.int = ...,
        canceled_messages_count: builtins.int = ...,
        errored_messages_count: builtins.int = ...,
        earliest_deadline: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["earliest_deadline", b"earliest_deadline"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["canceled_messages_count", b"canceled_messages_count", "completed_messages_count", b"completed_messages_count", "earliest_deadline", b"earliest_deadline", "errored_messages_count", b"errored_messages_count", "invisible_messages_count", b"invisible_messages_count", "pending_messages_count", b"pending_messages_count", "running_messages_count", b"running_messages_count"]) -> None: ...

global___GetQueueStateResponse = GetQueueStateResponse

@typing_extensions.final
class Queue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Options(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _Type:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Queue.Options._Type.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            SIMPLE: Queue.Options._Type.ValueType  # 0
            EXCLUSIVE: Queue.Options._Type.ValueType  # 1

        class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
        SIMPLE: Queue.Options.Type.ValueType  # 0
        EXCLUSIVE: Queue.Options.Type.ValueType  # 1

        TYPE_FIELD_NUMBER: builtins.int
        DEQUEUE_ATTEMPTS_FIELD_NUMBER: builtins.int
        LEASE_DURATION_FIELD_NUMBER: builtins.int
        EXCLUSIVITY_KEY_FIELD_NUMBER: builtins.int
        INVISIBILITY_DURATION_FIELD_NUMBER: builtins.int
        type: global___Queue.Options.Type.ValueType
        dequeue_attempts: builtins.int
        lease_duration: builtins.int
        exclusivity_key: builtins.str
        invisibility_duration: builtins.int
        def __init__(
            self,
            *,
            type: global___Queue.Options.Type.ValueType = ...,
            dequeue_attempts: builtins.int = ...,
            lease_duration: builtins.int = ...,
            exclusivity_key: builtins.str = ...,
            invisibility_duration: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["dequeue_attempts", b"dequeue_attempts", "exclusivity_key", b"exclusivity_key", "invisibility_duration", b"invisibility_duration", "lease_duration", b"lease_duration", "type", b"type"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def metadata(self) -> global___Queue.Options: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        metadata: global___Queue.Options | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["metadata", b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["metadata", b"metadata", "name", b"name"]) -> None: ...

global___Queue = Queue
