# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import chronoqueue_pb2 as chronoqueue__pb2


class ChronoQueueStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateQueue = channel.unary_unary(
                '/chronoqueue.api.chronoqueue.v1.ChronoQueue/CreateQueue',
                request_serializer=chronoqueue__pb2.CreateQueueRequest.SerializeToString,
                response_deserializer=chronoqueue__pb2.CreateQueueResponse.FromString,
                )
        self.DeleteQueue = channel.unary_unary(
                '/chronoqueue.api.chronoqueue.v1.ChronoQueue/DeleteQueue',
                request_serializer=chronoqueue__pb2.DeleteQueueRequest.SerializeToString,
                response_deserializer=chronoqueue__pb2.DeleteQueueResponse.FromString,
                )
        self.PostMessage = channel.unary_unary(
                '/chronoqueue.api.chronoqueue.v1.ChronoQueue/PostMessage',
                request_serializer=chronoqueue__pb2.PostMessageRequest.SerializeToString,
                response_deserializer=chronoqueue__pb2.PostMessageResponse.FromString,
                )
        self.GetNextMessage = channel.unary_unary(
                '/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetNextMessage',
                request_serializer=chronoqueue__pb2.GetNextMessageRequest.SerializeToString,
                response_deserializer=chronoqueue__pb2.GetNextMessageResponse.FromString,
                )
        self.AcknowledgeMessage = channel.unary_unary(
                '/chronoqueue.api.chronoqueue.v1.ChronoQueue/AcknowledgeMessage',
                request_serializer=chronoqueue__pb2.AcknowledgeMessageRequest.SerializeToString,
                response_deserializer=chronoqueue__pb2.AcknowledgeMessageResponse.FromString,
                )
        self.RenewMessageLease = channel.unary_unary(
                '/chronoqueue.api.chronoqueue.v1.ChronoQueue/RenewMessageLease',
                request_serializer=chronoqueue__pb2.RenewMessageLeaseRequest.SerializeToString,
                response_deserializer=chronoqueue__pb2.RenewMessageLeaseResponse.FromString,
                )
        self.PeekQueueMessages = channel.unary_unary(
                '/chronoqueue.api.chronoqueue.v1.ChronoQueue/PeekQueueMessages',
                request_serializer=chronoqueue__pb2.PeekQueueMessagesRequest.SerializeToString,
                response_deserializer=chronoqueue__pb2.PeekQueueMessagesResponse.FromString,
                )
        self.GetQueueState = channel.unary_unary(
                '/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetQueueState',
                request_serializer=chronoqueue__pb2.GetQueueStateRequest.SerializeToString,
                response_deserializer=chronoqueue__pb2.GetQueueStateResponse.FromString,
                )


class ChronoQueueServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewMessageLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PeekQueueMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChronoQueueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQueue,
                    request_deserializer=chronoqueue__pb2.CreateQueueRequest.FromString,
                    response_serializer=chronoqueue__pb2.CreateQueueResponse.SerializeToString,
            ),
            'DeleteQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteQueue,
                    request_deserializer=chronoqueue__pb2.DeleteQueueRequest.FromString,
                    response_serializer=chronoqueue__pb2.DeleteQueueResponse.SerializeToString,
            ),
            'PostMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PostMessage,
                    request_deserializer=chronoqueue__pb2.PostMessageRequest.FromString,
                    response_serializer=chronoqueue__pb2.PostMessageResponse.SerializeToString,
            ),
            'GetNextMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextMessage,
                    request_deserializer=chronoqueue__pb2.GetNextMessageRequest.FromString,
                    response_serializer=chronoqueue__pb2.GetNextMessageResponse.SerializeToString,
            ),
            'AcknowledgeMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeMessage,
                    request_deserializer=chronoqueue__pb2.AcknowledgeMessageRequest.FromString,
                    response_serializer=chronoqueue__pb2.AcknowledgeMessageResponse.SerializeToString,
            ),
            'RenewMessageLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewMessageLease,
                    request_deserializer=chronoqueue__pb2.RenewMessageLeaseRequest.FromString,
                    response_serializer=chronoqueue__pb2.RenewMessageLeaseResponse.SerializeToString,
            ),
            'PeekQueueMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.PeekQueueMessages,
                    request_deserializer=chronoqueue__pb2.PeekQueueMessagesRequest.FromString,
                    response_serializer=chronoqueue__pb2.PeekQueueMessagesResponse.SerializeToString,
            ),
            'GetQueueState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueState,
                    request_deserializer=chronoqueue__pb2.GetQueueStateRequest.FromString,
                    response_serializer=chronoqueue__pb2.GetQueueStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chronoqueue.api.chronoqueue.v1.ChronoQueue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChronoQueue(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chronoqueue.api.chronoqueue.v1.ChronoQueue/CreateQueue',
            chronoqueue__pb2.CreateQueueRequest.SerializeToString,
            chronoqueue__pb2.CreateQueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chronoqueue.api.chronoqueue.v1.ChronoQueue/DeleteQueue',
            chronoqueue__pb2.DeleteQueueRequest.SerializeToString,
            chronoqueue__pb2.DeleteQueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chronoqueue.api.chronoqueue.v1.ChronoQueue/PostMessage',
            chronoqueue__pb2.PostMessageRequest.SerializeToString,
            chronoqueue__pb2.PostMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNextMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetNextMessage',
            chronoqueue__pb2.GetNextMessageRequest.SerializeToString,
            chronoqueue__pb2.GetNextMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcknowledgeMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chronoqueue.api.chronoqueue.v1.ChronoQueue/AcknowledgeMessage',
            chronoqueue__pb2.AcknowledgeMessageRequest.SerializeToString,
            chronoqueue__pb2.AcknowledgeMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RenewMessageLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chronoqueue.api.chronoqueue.v1.ChronoQueue/RenewMessageLease',
            chronoqueue__pb2.RenewMessageLeaseRequest.SerializeToString,
            chronoqueue__pb2.RenewMessageLeaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PeekQueueMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chronoqueue.api.chronoqueue.v1.ChronoQueue/PeekQueueMessages',
            chronoqueue__pb2.PeekQueueMessagesRequest.SerializeToString,
            chronoqueue__pb2.PeekQueueMessagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetQueueState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetQueueState',
            chronoqueue__pb2.GetQueueStateRequest.SerializeToString,
            chronoqueue__pb2.GetQueueStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
