# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.timestamp_pb2
from . import service_pb2


class ChronoQueueBase(abc.ABC):

    @abc.abstractmethod
    async def CreateQueue(self, stream: 'grpclib.server.Stream[service_pb2.CreateQueueRequest, service_pb2.CreateQueueResponse]') -> None:
        pass

    @abc.abstractmethod
    async def DeleteQueue(self, stream: 'grpclib.server.Stream[service_pb2.DeleteQueueRequest, service_pb2.DeleteQueueResponse]') -> None:
        pass

    @abc.abstractmethod
    async def PostMessage(self, stream: 'grpclib.server.Stream[service_pb2.PostMessageRequest, service_pb2.PostMessageResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetNextMessage(self, stream: 'grpclib.server.Stream[service_pb2.GetNextMessageRequest, service_pb2.GetNextMessageResponse]') -> None:
        pass

    @abc.abstractmethod
    async def AcknowledgeMessage(self, stream: 'grpclib.server.Stream[service_pb2.AcknowledgeMessageRequest, service_pb2.AcknowledgeMessageResponse]') -> None:
        pass

    @abc.abstractmethod
    async def RenewMessageLease(self, stream: 'grpclib.server.Stream[service_pb2.RenewMessageLeaseRequest, service_pb2.RenewMessageLeaseResponse]') -> None:
        pass

    @abc.abstractmethod
    async def PeekQueueMessages(self, stream: 'grpclib.server.Stream[service_pb2.PeekQueueMessagesRequest, service_pb2.PeekQueueMessagesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetQueueState(self, stream: 'grpclib.server.Stream[service_pb2.GetQueueStateRequest, service_pb2.GetQueueStateResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/CreateQueue': grpclib.const.Handler(
                self.CreateQueue,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.CreateQueueRequest,
                service_pb2.CreateQueueResponse,
            ),
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/DeleteQueue': grpclib.const.Handler(
                self.DeleteQueue,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.DeleteQueueRequest,
                service_pb2.DeleteQueueResponse,
            ),
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/PostMessage': grpclib.const.Handler(
                self.PostMessage,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.PostMessageRequest,
                service_pb2.PostMessageResponse,
            ),
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetNextMessage': grpclib.const.Handler(
                self.GetNextMessage,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.GetNextMessageRequest,
                service_pb2.GetNextMessageResponse,
            ),
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/AcknowledgeMessage': grpclib.const.Handler(
                self.AcknowledgeMessage,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.AcknowledgeMessageRequest,
                service_pb2.AcknowledgeMessageResponse,
            ),
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/RenewMessageLease': grpclib.const.Handler(
                self.RenewMessageLease,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.RenewMessageLeaseRequest,
                service_pb2.RenewMessageLeaseResponse,
            ),
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/PeekQueueMessages': grpclib.const.Handler(
                self.PeekQueueMessages,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.PeekQueueMessagesRequest,
                service_pb2.PeekQueueMessagesResponse,
            ),
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetQueueState': grpclib.const.Handler(
                self.GetQueueState,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.GetQueueStateRequest,
                service_pb2.GetQueueStateResponse,
            ),
        }


class ChronoQueueStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.CreateQueue = grpclib.client.UnaryUnaryMethod(
            channel,
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/CreateQueue',
            service_pb2.CreateQueueRequest,
            service_pb2.CreateQueueResponse,
        )
        self.DeleteQueue = grpclib.client.UnaryUnaryMethod(
            channel,
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/DeleteQueue',
            service_pb2.DeleteQueueRequest,
            service_pb2.DeleteQueueResponse,
        )
        self.PostMessage = grpclib.client.UnaryUnaryMethod(
            channel,
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/PostMessage',
            service_pb2.PostMessageRequest,
            service_pb2.PostMessageResponse,
        )
        self.GetNextMessage = grpclib.client.UnaryUnaryMethod(
            channel,
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetNextMessage',
            service_pb2.GetNextMessageRequest,
            service_pb2.GetNextMessageResponse,
        )
        self.AcknowledgeMessage = grpclib.client.UnaryUnaryMethod(
            channel,
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/AcknowledgeMessage',
            service_pb2.AcknowledgeMessageRequest,
            service_pb2.AcknowledgeMessageResponse,
        )
        self.RenewMessageLease = grpclib.client.UnaryUnaryMethod(
            channel,
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/RenewMessageLease',
            service_pb2.RenewMessageLeaseRequest,
            service_pb2.RenewMessageLeaseResponse,
        )
        self.PeekQueueMessages = grpclib.client.UnaryUnaryMethod(
            channel,
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/PeekQueueMessages',
            service_pb2.PeekQueueMessagesRequest,
            service_pb2.PeekQueueMessagesResponse,
        )
        self.GetQueueState = grpclib.client.UnaryUnaryMethod(
            channel,
            '/chronoqueue.api.chronoqueue.v1.ChronoQueue/GetQueueState',
            service_pb2.GetQueueStateRequest,
            service_pb2.GetQueueStateResponse,
        )
